alunosDo1ACEVA = ['ANA GABRIELA RODRIGUES CABRAL', 'BEATRIZ DALAVA PINTO DE OLIVEIRA', 'CAIO WILLIAN MELO DA SILVA', 'EMANUELA CRISITNA MARTIMBIANCO DE OLIVEIRA', 'ERICA MONTEIRO MEDEIROS', 'FERNANDA CORREIA LOPES DA SILVA', 'GABRIEL DE FREITAS HOFFMANN', 'GABRIEL JAKUBOWSKI DE OLIVEIRA', 'GABRIEL MEDEIROS LEITE', 'GABRIELY DE JESUS ANTONIO', 'GLAUCO ALEXSANDRO BRESSAN DE ALMEIDA', 'HELOIZA DA SILVA HERNACKI', 'IZABELLY VITORIA LOPES DA SILVA', 'JAYLON DE OLIVEIRA AMORIM', 'JOAO VITOR ELIAS ROLIN', 'JOAO VITOR SALES PATEREK', 'LAIS SANTOS LOPES', 'NICOLAS BALADELLI DE OLIVEIRA FREITAS', 'RENATO DE SOUZA SANTOS', 'VANESSA WILTTE CAMARGO', 'VICTOR HUGO GOUVEIA DE AGUIAR', 'VINICIUS BITTENCOURT'];
alunosDo2ACEVA = ['ANDRESSA KAUANA REIS SANTOS', 'ANGELA SCHWERTNER', 'CARLOS GABRIEL DE OLIVEIRA SANTOS', 'EDSON GABRIEL MARQUES DA SILVA', 'EMILY VITÓRIA NANIS PIMENTA', 'GUILHERME OLIVEIRA PASSOS', 'ISABELLY SANTOS BARROS', 'ISABÉLLY VITÓRIA DA SILVA SANTOS', 'JHENIFER FERNANDA POLIZELLI JENOCA', 'KESSIA VITORIA RODRIGUES RUBIO', 'LARISSA GABRIELY SALES DE ALMEIDA', 'LUCIANA SANTIAGO VIEIRA', 'LUIZ FERNANDO SOUZA DE ANDRADE', 'MANUELLA FORMIGONI DOS SANTOS', 'MARIA CLARA PAIÉ DA SILVA', 'MAYSA BARTMANOVICZ SILVA', 'RAFAEL REKEL DE FREITAS', 'YASMIN SANTOS DE SOUZA', 'VANESSA FERNANDA DE SOUZA'];
alunosDo7ACEVA = ['ANDREY DA SILVA ALVES', 'ARTHUR SANTOS DE OLIVEIRA', 'BRENDA YASMIN ALMEIDA DE CAMARGO', 'DAVI DE LIMA SILVA', 'HELLOA GOMES PAIVA', 'ISABELLA DA SILVA MURTA', 'ISABELLY JAKUBOWSKI PEREIRA', 'JOÃO PAULO REVESSE PALHARES', 'JOÃO PEDRO MELO DA CRUZ', 'KEVERTON LEANDRO DE OLIVEIRA AMARAL', 'LARYSSA SILVA DOS SANTOS', 'LAUDEYR ANDREY DA SILVA', 'LUIZ FELIPE DA SILVA GONÇALVES', 'MARCO DANIEL RODRIGUES VICTORINO CALDAS', 'MARIA LAURA MIGUEL DE ALMEIDA', 'MATHEUS HENRIQUE SANTOS DA SILVA', 'NATALIA DA SILVA SOUZA', 'NÍCOLAS EMMANUEL HERMACKI DE OLIVEIRA', 'NICOLAS FELIPE SALES DA SILVA', 'RENATO KAUAN VIANA', 'ENZO RICARDO CANETE DE LIMA'];
alunosDo8ACEVA = ['ADRIAN GABRIEL DOS SANTOS BRITO DA SILVA', 'ALLIFER EDUARDO DA SILVA GONÇALVES', 'AMANDA TIMOTEO JORGE', 'ANAIRY ALAIS GOMES DE GODOI', 'ARTHUR GOMES BUENO', 'CARLOS ALEXANDRE DA SILVA GONÇALVES', 'CAUÂ WILLIAN MELO DA SILVA', 'DOUGLAS JOSÉ NUNES DE MORAES', 'EDUARDA MORAIS DE OLIVEIRA', 'GABRIELLY BARONI SILVA', 'GEOVANNA DA SILVA', 'GUSTAVO BARTMANOVICZ SILVA', 'IGOR CAMPANHOLI ANTUNES', 'KETELLEN RAYSSA MURTA BALAN', 'KETHELIN FERNANDA ARRUDA DE SOUZA', 'LARA SANTOS AMORIN', 'MARIA CLARA CRUZ SOUZA', 'MARIA EDUARDA GUIMARÃES FARIA', 'MARIANE NEVES TRIVILIN', 'NAYARA CAETANO LOPES', 'NICOLE FERNANDA DOS SANTOS MORAIS', 'PEDRO DE SOUZA OGIBOWSKI', 'PEDRO HENRIQUE SOUZA DE ANDRADE', 'SARA NATIÉLI DE OLIVEIRA MOREIRA', 'VITÓRIA DE LIMA DA SILVA', 'YASMIN EDUARDA MOREIRA DA SILVA'];
alunosDo9ACEVA = ['CARLOS EDUARDO DOS SANTOS TEIXEIRA', 'CAUÂ RAFAEL SILVA MURTA', 'CELSO GUILHERME DE OLIVEIRA', 'FELIPE SOARES DOS SANTOS SILVA', 'GABRIEL OLIVEIRA ROMÃO', 'GUILHERME NUNES DE MORAES', 'GUSTAVO BENASSI CAMPANHOLI', 'GUSTAVO DE OLIVEIRA', 'JOÃO VICTOR MURTA ALMEIDA', 'JOSÉ GUILHERME GONÇALVES GOMES', 'JULIA SANTIAGO DOS SANTOS', 'JULIO CESAR AUGUSTO FELIPE', 'KATIELE CRISTINA DUVAL DALAVA', 'KAUAN VINICIUS AMARAL DE OLIVEIRA', 'KELVIN MARTINS DOS SANTOS DE LIMA', 'LAILA VITORIA DOS SANTOS LIMA SILVA', 'LOYANE VITÓRIA SALES DE ALMEIDA', 'LUIZ FERNANDO SANTOS DE MORAIS', 'MARIA GABRIELLY RODRIGUES HERCULANO', 'RODRIGO GOMES ACUNA', 'SABRINA GOMES DE OLIVEIRA', 'TAYNÁ SANTANA DA SILVA', 'WELISON DO CARMO MARTIMBIANCO', 'WILLIAM GABRIEL SANTOS DA SILVEIRA', 'LAYLA BEZERRA HERMACKI', 'MAILON GABRIEL CARDOSO EVARISTO'];
alunosDo1BCEVA = ['ALDERLEIO FERNANDO SILVA FERREIRA JUNIOR', 'BRAYAN FERREIRA DE GODOI', 'CLEITON TUNIQUES SILVA', 'FELIPE MEDEIROS DA SILVA', 'GABRIEL TOMAZ DA SILVA', 'GUILHERME TUNIQUES DA SILVA', 'JOÃO VITOR SUSKO DE OLIVEIRA', 'JOSÉ GUILHERME NOGUEIRA SANTOS', 'JUNIOR CESAR MARTIMBIANCO TARDIM', 'KAUAN HENRIQUE FERREIRA DA SILVA', 'KAUAN NOIBAL DE OLIVEIRA', 'KAUAN WILIAN DE JESUS SILVA', 'KAYKE GABRIEL GONÇALVES DO VALE', 'KAYKE MARTIMBIANCO FERREIRA', 'LUCAS ANTONIO DE ARAUJO MALDONADO', 'LUCAS GABRIEL NEVES ALVES', 'LUCILENE SIQUEIRA LIMA', 'LUIZ HENRIQUE DA SILVA GONÇALVES', 'RENATO SALES DA SILVA', 'RILDO VIEIRA DOS SANTOS JUNIOR', 'WILFRIDO GOMES ACUNA', 'ISABELA CANDIDO SOARES', 'MAICON DA ROCHA FRANCISCO'];
alunosDo2BCEVA = ['ALEXSANDRA DOS SANTOS HERNACKI', 'ALISSON JUNIOR GONCALVES FLEITAS', 'BRUNA MIKAELE GOMES DE OLIVEIRA', 'CARLOS EDUARDO JANOCA DA SILVA', 'CARLOS MANOEL DA SILVA VALE', 'ERIC MONTEIRO MEDEIROS', 'JADSON THIAGO SILVA E SILVA', 'JOÃO VICTOR SOARES DA CRUZ', 'LAYRA MARCELINA CABRAL FRANCISCO', 'LUÍZA RAFAELLA SILVA MURTA', 'MARIA EDUARDA CAETANO TEIXEIRA', 'PABLO HENRIQUE DO CARMO MARTIMBIANCO', 'PEDRO HENRIQUE DE LIMA SILVA', 'PEDRO HENRIQUE RIBEIRO NEVES', 'WENDEL DALÓLIO FELIX', 'GUILHERME PEREIRA DA SILVA', 'ALLANA KAROLYNE DE OLIVEIRA COSTA'];
alunosDo6BCEVA = ['AGATA FERREIRA DA SILVA', 'ANA CLARA DE MORAIS SOARES','ANDRIELLY DE JESUS SILVA', 'EMANUEL DE OLIVEIRA QUARESMA', 'FERNANDA ROSSI DA SILVA', 'JULIA GABRIELY GOMES DE SOUZA', 'KAIQUE PEREIRA DA SILVA MACEDO', 'KAUANE CRISTINE DA SILVA MURTA', 'LARISSA NOGUEIRA DE OLIVEIRA', 'LETICIA VITÓRIA RAMOS CRISPIM', 'MARIA CLARA TUNIQUES DA SILVA', 'MARIA EDUARDA LIMA DE OLIVEIRA', 'MELLODHE NAÍRA RODRIGUES BRACCI', 'NICOLAS GABRIEL JESUS DA SILVA', 'SARAH DE LIMA DA SILVA', 'VITÓRIA FERNANDA DA SILVA FONSECA', 'MAIK EDUARDO SANTOS BELUCI', 'MIGUEL ALESSANDRO MARQUES PUERTA', 'MARIA CLARA ARRIGO DA LUZ PEREIRA'];
alunosDo7BCEVA = ['ADRYAN FERREIRA DE SOUZA SCHON', 'DEBORA VITORIA RODRIGUES MARQUES', 'GEOVANA WILTTE', 'JOÃO GUILHERME REKEL DE FREITAS RIBEIRO', 'KAIO VINICIUS RODRIGUES TENÓRIO DA SILVA', 'MARIZA DA SILVA SANTOS', 'MATHEUS EDUARDO DA SILVA ROSSETTI', 'PAULO EMILIO RODRIGUES PEREIRA', 'PEDRO HENRIQUE DE CARVALHO SILVA', 'PEDRO MIGUEL VIEIRA DOS SANTOS', 'RAFAEL VALDEIR DA SILVA DOS SANTOS', 'RENAN DIAS LADEIRA', 'RICHARD GABRIEL SOARES DA CRUZ', 'SARA SILVA SERVIDONI', 'THAÍSA TAINÁ SOARES DE SOUZA', 'VINICIUS LISBOA CORDEIRO', 'LUCAS VINICIUS DA ROCHA COSTA', 'ZAFENATT EMANUEL BARROS DE ALMEIDA', 'MARIA EDUARDA RIOS', 'AMABILLY DOS SANTOS LIMA SILVA', 'JULIA BIANCA SILVA DA CRUZ', 'MURILO JOSIAS DOS SANTOS ORTIZ'];
alunosDo8BCEVA = ['AGATHA CALADO BORGES', 'CAMILA TOMAZ DA SILVA', 'CRISTIANO RONALDO RIBEIRO DA MOTA', 'DAIANE BRAGA SANTANA', 'EMILLY DA SILVA PINHEIRO', 'EMILY FERNANDA MONTEIRO LIMA', 'ERICK GABRIEL DOS SANTOS ALVES', 'ESTEFFANI LOHRAINE PAVANELI DA SILVA', 'GUILHERME MARTIMBIANCO TARDIM', 'GUSTAVO VENITTE MARKO', 'ISABELLY SANTANA MEDEIROS', 'KAUANI CRISTINY MORBEK SANTANA', 'KAUÊ GUSTAVO GOMES DA SILVA', 'LARYSSA EDUARDA VENITTE MARKO', 'LUCIANO SIQUEIRA VIEIRA', 'MAURILIO EDUARDO DOS SANTOS OLIVEIRA', 'RAFAEL APARECIDO MOURA LASARO', 'RAUAN DE OLIVEIRA PONTES', 'RENATA FERNANDA SALES DA SILVA', 'WILLIANS MADSON RODRIGUES BRACCI', 'YASMIM VITÓRIA VAZ BORLITA', 'EMILY GABRIELY ALVES COUTO', 'MARCOS GABRIEL DOS SANTOS DE ALMEIDA'];
alunosDo9BCEVA = ['ANA MARIA DE OLIVEIRA MORAES', 'CAMILY EDUARDA LIMA DE JESUS', 'CLARA GABRIELLY RODRIGUES SALES DE OLIVEIRA', 'EDUARDA ANTONIO MORAES', 'GABRIEL ANACLETO DE ALMEIDA', 'JONAS SCHWERTNER RAMOS', 'JULIANA ARANHA GALVES DOS SANTOS', 'LAYENNI SOFIA MOREIRA DA SILVA', 'LUIS MARCOS DA SILVA SANTOS', 'LUIZ FERNANDO DE CARVALHO SILVA', 'LUIZ FERNANDO RIBEIRO GALVÃO', 'LUIZ JUNIOR RIBEIRO DA SILVA', 'MARCO ANTONIO DE OLIVEIRA QUARESMA', 'MARIA EDUARDA LÔR PEREIRA', 'MARIA EDUARDA SANTIAGO CORREIA', 'OTÁVIO HENRIQUE DE MORAIS SOARES', 'RIAN MURILO PAULINO SALES', 'SARA FREITA DE SÁ', 'VITOR HUGO DA SILVA ROSSETTI', 'VITORIA LISBOA CORDEIRO', 'YURI DALOLIO LOPES', 'JOÃO VICTOR DE MOURA TESSAROLLO', 'YASMIM LAIS FRABRICIO DA SILVA', 'RAFAELLA RIOS', 'JOÃO PEDRO ARRIGO DA LUZ PEREIRA'];

alunosSelecionados = [];

const tabela = document.querySelector('#tabela')
selectionAlunos(document.location.search)

function selectionAlunos(point) {
    if (point == '?CEVA1A') {
        alunosSelecionados = alunosDo1ACEVA;
    } else if (point == '?CEVA2A') {
        alunosSelecionados = alunosDo2ACEVA;
    } else if (point == '?CEVA3A') {
        alunosSelecionados = alunosDo3ACEVA;
    } else if (point == '?CEVA7A') {
        alunosSelecionados = alunosDo7ACEVA;
    } else if (point == '?CEVA8A') {
        alunosSelecionados = alunosDo8ACEVA;
    } else if (point == '?CEVA9A') {
        alunosSelecionados = alunosDo9ACEVA;
    } else if (point == '?CEVA1B') {
        alunosSelecionados = alunosDo1BCEVA;
    } else if (point == '?CEVA2B') {
        alunosSelecionados = alunosDo2BCEVA;
    } else if (point == '?CEVA3B') {
        alunosSelecionados = alunosDo3BCEVA;
    } else if (point == '?CEVA6B') {
        alunosSelecionados = alunosDo6BCEVA;
    } else if (point == '?CEVA7B') {
        alunosSelecionados = alunosDo7BCEVA;
    } else if (point == '?CEVA8B') {
        alunosSelecionados = alunosDo8BCEVA;
    } else if (point == '?CEVA9B') {
        alunosSelecionados = alunosDo9BCEVA;
    } else if (point == '') {
        alert("Acesse Novamente");
    } 
} 

alunosSelecionados.forEach(element => {
    tabela.innerHTML = `${tabela.innerHTML} <tr> <td>${element}</td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> <td><input type="checkbox"></td> </tr>`
});